# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np
arr=np.random.rand(4,7)*20
minim=arr.min()
maxim=arr.max()
ar=(arr-minim)/(maxim-minim)
ar

array([[0.52185724, 0.99027279, 0.89790522, 0.79709137, 0.36799214,
        0.30757618, 0.95025287],
       [0.76880309, 1.        , 0.57630178, 0.11887496, 0.48619729,
        0.85588311, 0.21295035],
       [0.49305393, 0.97573315, 0.55942962, 0.86001108, 0.43676664,
        0.10041225, 0.06671354],
       [0.20439538, 0.38672006, 0.        , 0.57502513, 0.34373217,
        0.6066512 , 0.08623474]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import numpy as np
arr=np.random.randint(10, size=(8,10))
summ=np.sum(arr, axis=1)
summin=summ.argmin()

print(arr)
print(summ)
print(summin)
print(arr[summin])


[[4 3 6 5 5 3 0 3 9 1]
 [1 8 5 1 0 1 2 0 4 2]
 [3 3 1 7 4 5 7 8 8 3]
 [4 7 1 1 9 5 0 9 7 6]
 [1 9 4 3 1 4 8 6 7 5]
 [5 7 5 7 5 6 4 2 5 4]
 [4 0 7 5 8 1 0 0 8 6]
 [4 6 4 3 0 7 9 4 8 1]]
[39 24 49 49 48 50 39 46]
1
[1 8 5 1 0 1 2 0 4 2]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import numpy as np
arr1=np.array([0,0,0])#np.random.randint(10,size=(1,3))
arr2=np.array([0,0,1])#np.random.randint(10,size=(1,3))
print(arr1)
print(arr2)
rez=np.linalg.norm(arr1-arr2)
print(rez)

[0 0 0]
[0 0 1]
1.0


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:

A=np.array([[-1,2,4],[-3,1,2],[-3,0,1]])
B=np.array([[3,-1],[2,1]])
C=np.array([[7,21],[11,8],[8,4]])
x=-np.linalg.inv(A)@C@np.linalg.inv(B)

print(A@x@B)


[[ -7. -21.]
 [-11.  -8.]
 [ -8.  -4.]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
a=np.loadtxt(r"/content/drive/MyDrive/Colab Notebooks/minutes_n_ingredients.csv",dtype=np.int32, skiprows=1,delimiter=',')
a[:5]

Mounted at /content/drive


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [11]:
print("сред ", np.mean(a, axis=0))
print("мин ",np.min(a, axis=0))
print("макс ",np.max(a,axis=0))
print("медиана ",np.median(a,axis=0))


сред  [2.22064324e+05 2.16010017e+04 9.05528000e+00]
мин  [38  0  1]
макс  [    537671 2147483647         39]
медиана  [2.071935e+05 4.000000e+01 9.000000e+00]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [2]:
dataset= np.copy(a)
q = np.quantile(a[:,1],0.75)
a[:,1] = a[:,1].clip(max=q)
a

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [31]:
dataset= np.copy(a)
rez= len(dataset)-np.count_nonzero(dataset[:,1])

print("Количество рецептов:", rez)
dataset[dataset[:,1]==0,1]=1
rez= len(dataset)-np.count_nonzero(dataset[:,1])
print(rez)

Количество рецептов: 479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [15]:
dataset1= np.copy(a)
rez= len(np.unique(dataset1[:,1:]))
rez

656

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [3]:
dataset1= np.copy(a)
rez= np.unique(dataset1[:,2:])
rez

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39], dtype=int32)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [45]:
dataset=np.copy(a)
dataset[dataset[:,2]<5]

array([[204134,      5,      3],
       [ 25623,      6,      4],
       [484223,     18,      4],
       ...,
       [227056,     30,      4],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [19]:
dataset2 = np.copy(a)
dataset2 = np.c_[dataset2, np.zeros(np.shape(dataset2)[0])]
dataset2 = dataset2.astype(float, copy=False)
dataset2[:,3] += np.divide(dataset2[:, 2], dataset2[:, 1], out=dataset2[:, 2], where=dataset2[:, 1] != 0)
print(dataset2)

[[1.27244000e+05 6.00000000e+01 2.66666667e-01 2.66666667e-01]
 [2.38910000e+04 2.50000000e+01 2.80000000e-01 2.80000000e-01]
 [9.47460000e+04 1.00000000e+01 6.00000000e-01 6.00000000e-01]
 ...
 [4.98432000e+05 6.50000000e+01 2.30769231e-01 2.30769231e-01]
 [3.70915000e+05 5.00000000e+00 8.00000000e-01 8.00000000e-01]
 [8.19930000e+04 1.40000000e+02 1.00000000e-01 1.00000000e-01]]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [49]:
dataset= a[a[:, 1]. argsort ()[::-1]]
print(np.mean(dataset[:100,2]))

[[    261647 2147483647          8]
 [    216215     259260          7]
 [    425681     259205          2]
 [     98912     216015          4]
 [     70551     201610          7]
 [    236340     146880          5]
 [    242032     132495          3]
 [    184528     129620          3]
 [    236274     129615          5]
 [    236281     129615          5]]
[ 8  7  2  4  7  5  3  3  5  5  4  2  4  3  9  2  2  3  3  7  5  4  3 22
  4 15  8  3  2  5  9  3  3 17  7  3  8  4  6  5  5  6  4  2  8  6  8  6
  8  3  4  4 10 12 11 11  5  4  4  9 10  7 12  5  9  6  3  6  9  2  4 13
  3  6  5 13  8  5  5 13 10 17  8  5  8  8  3  8 14  3  8 12  8 13  7  6
  7  8  4  6]
6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [37]:
rand=np.random.randint(10000, size=10)
a[rand,:]


array([[ 32860,      2,      7],
       [ 28075,     15,      6],
       [180800,      5,      3],
       [ 50005,      5,      8],
       [164062,     70,     14],
       [515426,    510,     10],
       [ 82783,     31,      5],
       [312914,     20,      3],
       [159184,     60,     13],
       [180662,     10,     11]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [32]:
dataset2 = np.copy(a)
length = len(dataset2)
sred = np.sum(dataset2[:,2]) / length  
rez_mas = dataset2[dataset2[:,2] < sred]                
result = (len(rez_mas)/length * 100) # Результат в процентах
print(result,'%')

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [4]:
dataset2 = np.copy(a)          
b = np.zeros((len(dataset2),4))
b[:,:-1] = dataset2
b[:,3] = np.where(dataset2[:,2]<=5, 0, (np.where(dataset2[:,1]>20, 1, 0)))
b

array([[1.27244e+05, 6.00000e+01, 1.60000e+01, 1.00000e+00],
       [2.38910e+04, 2.50000e+01, 7.00000e+00, 1.00000e+00],
       [9.47460e+04, 1.00000e+01, 6.00000e+00, 0.00000e+00],
       ...,
       [4.98432e+05, 6.50000e+01, 1.50000e+01, 1.00000e+00],
       [3.70915e+05, 5.00000e+00, 4.00000e+00, 0.00000e+00],
       [8.19930e+04, 6.50000e+01, 1.40000e+01, 1.00000e+00]])

13. Выведите процент "простых" рецептов в датасете

In [5]:
length = len(dataset2)
rez= length-np.count_nonzero(b[:,3])               
result = (rez/length * 100) 
result

34.36

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.